obstacle_range: 2.0
raytrace_range: 2.0
footprint: [[0.08,0.25],[-0.45,0.25],[-0.45,-0.25],[0.08,-0.25]]
robot_radius: 0.36
inflation_radius: 2.3
cost_scaling_factor: 10.0

publish_voxel_map: false

observation_sources: tom_3d

cost_scaling_factor: 10

observation_sources: laser_scan_pls

laser_scan_pls: {sensor_frame: sick_pls_link , data_type: LaserScan, topic: sick_pls/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3}



